version: '2'

# tested 4.0.2 server

services:
  neo4j:
    image: neo4j:4.0.2
    hostname: neo4j
    domainname: koakh.com
    container_name: neo4j
    restart: unless-stopped
    ports:
      # http rest api - open only internally, not encrypted
      - "7474:7474"
      # https rest api
      - "7473:7473"
      # bolt
      - "7687:7687"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/data:/var/lib/neo4j/data
      - ./volumes/logs:/var/lib/neo4j/logs
      # - ./volumes/conf:/var/lib/neo4j/conf
      - ./volumes/plugins:/var/lib/neo4j/plugins
      - ./volumes/import:/var/lib/neo4j/import
      - ./volumes/certificates:/var/lib/neo4j/certificates
    environment:
      - NEO4J_dbms_connector_http_enabled=false
      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_https_ssl__policy=default
      - NEO4J_dbms_ssl_policy_https_base__directory=/var/lib/neo4j/certificates
      - NEO4J_dbms_ssl_policy_https_private__key=/var/lib/neo4j/certificates/neo4j.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=/var/lib/neo4j/certificates/neo4j.cert
      - NEO4J_dbms_ssl_policy_https_revoked__dir=/var/lib/neo4j/certificates/revoked
      - NEO4J_dbms_ssl_policy_https_trusted__dir=/var/lib/neo4j/certificates/trusted
      # - NEO4J_dbms_ssl_policy_https_client__auth=NONE
      # bolt
      - NEO4J_dbms_connector_bolt_tls__level=REQUIRED
      # required to work with neo4j-driver js - NOT TESTED YET
      # - NEO4J_dbms_connector_bolt_tls__level=OPTIONAL
      - NEO4J_bolt_ssl__policy=default
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/var/lib/neo4j/certificates
      - NEO4J_dbms_ssl_policy_bolt_private__key=/var/lib/neo4j/certificates/neo4j.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=/var/lib/neo4j/certificates/neo4j.cert
      - NEO4J_dbms_ssl_policy_bolt_revoked__dir=/var/lib/neo4j/certificates/revoked
      - NEO4J_dbms_ssl_policy_bolt_trusted__dir=/var/lib/neo4j/certificates/trusted
      # - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      # - NEO4J_dbms_connector_bolt__advertised_address=koakh.com:7687
      # - NEO4J_dbms_connector_default__advertised_address=koakh.com
      # - NEO4J_dbms_default__advertised__address=neo4j.koakh.com
      # allow non-local connections and this is achieved by updating conf/neo4j.conf and define parameter dbms.connectors.default_advertised_address=0.0.$
      - NEO4J_dbms_default__advertised__address=0.0.0.0
      # - NEO4J_dbms_connector_bolt__address=0.0.0.0:7687
      # fix: SessionExpired: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available t$
      # - NEO4J_dbms_connector_bolt_advertised__address=neo4j.koakh.com:7687
      # - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
      # - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
version: '2'

services:
  neo4j:
    image: neo4j:4.0.2
    hostname: neo4j
    domainname: koakh.com
    container_name: neo4j
    restart: unless-stopped
    ports:
      # http rest api - open only internally, not encrypted
      - "7474:7474"
      # https rest api
      - "7473:7473"
      # bolt
      - "7687:7687"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/data:/var/lib/neo4j/data
      - ./volumes/logs:/var/lib/neo4j/logs
      # - ./volumes/conf:/var/lib/neo4j/conf
      - ./volumes/plugins:/var/lib/neo4j/plugins
      - ./volumes/import:/var/lib/neo4j/import
      - ./volumes/certificates:/var/lib/neo4j/certificates
    environment:
      - NEO4J_dbms_connector_http_enabled=false
      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_https_ssl__policy=default
      - NEO4J_dbms_ssl_policy_https_base__directory=/var/lib/neo4j/certificates
      - NEO4J_dbms_ssl_policy_https_private__key=/var/lib/neo4j/certificates/neo4j.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=/var/lib/neo4j/certificates/neo4j.cert
      - NEO4J_dbms_ssl_policy_https_revoked__dir=/var/lib/neo4j/certificates/revoked
      - NEO4J_dbms_ssl_policy_https_trusted__dir=/var/lib/neo4j/certificates/trusted
      - NEO4J_dbms_connector_bolt_tls__level=REQUIRED
      - NEO4J_bolt_ssl__policy=default
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/var/lib/neo4j/certificates
      - NEO4J_dbms_ssl_policy_bolt_private__key=/var/lib/neo4j/certificates/neo4j.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=/var/lib/neo4j/certificates/neo4j.cert
      - NEO4J_dbms_ssl_policy_bolt_revoked__dir=/var/lib/neo4j/certificates/revoked
      - NEO4J_dbms_ssl_policy_bolt_trusted__dir=/var/lib/neo4j/certificates/trusted
      - NEO4J_dbms_default__advertised__address=0.0.0.0
